# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friendships',
            field=models.ManyToManyField(related_name='_user_friendships_+', to='exam.User'),
        ),
    ]
